Fetching user location weather
GSG-CF04/FlowX pull request #23
Opened 2021-12-01 12:39 UTC by AseelL

Resolves #13

2021-12-01 13:49 UTC, zaher-aa requested changes

2021-12-01 13:49 UTC, zaher-aa commented on js/home.js
> +
Format your code.

2021-12-01 13:49 UTC, zaher-aa commented on js/home.js
> +    )
format this too

2021-12-01 15:43 UTC, AseelL commented on js/home.js
> +    )
done

2021-12-01 16:46 UTC, sara219 requested changes
write a description comment before the functions, describe what the function do

2021-12-02 04:37 UTC, zaher-aa submitted a review, later dismissed

2021-12-02 06:26 UTC, sara219 approved these changes, later dismissed

2021-12-02 09:10 UTC, zaher-aa approved these changes

2021-12-02 09:12 UTC, sara219 approved these changes

2021-12-02 09:12 UTC, merged