fetch API and take the data we want it Relates #12
GSG-CF04/FlowX pull request #24
Opened 2021-12-01 15:14 UTC by husamkamal

2021-12-01 15:36 UTC, husamkamal commented
The Real Time 5h

2021-12-01 17:11 UTC, sara219 requested changes

2021-12-01 17:11 UTC, sara219 commented on js/home.js
> +        )
It is preferable not to use `document.write`, it's considered as a **"bad practice"**, it can block your page

[Why is document.write considered a "bad practice"?](https://newbedev.com/why-is-document-write-considered-a-bad-practice)

2021-12-01 17:11 UTC, sara219 commented on js/home.js
> +            e => document.write(e)
change the `e` to something more descriptive about errors

2021-12-01 17:11 UTC, sara219 commented on js/home.js
> +            showSeto("")
format your code using `Prettier`

2021-12-01 17:11 UTC, sara219 commented on js/home.js
> +            suggBox.innerHTML = arr
don't use `innerHTML` when you can use other safe property 

'innerHTML' Presents a Security Risk

2021-12-01 17:11 UTC, sara219 commented on js/home.js
> +    )
the `e` is the response from the API fetch ! change the return data  to a descriptive name instead of `e`

2021-12-01 17:11 UTC, sara219 commented on js/home.js
> +                return qq = '<span>' + qq + '</span>'
what is `qq` ! what data is assigned to it!! 
name your variables after more descriptive things

2021-12-01 17:11 UTC, sara219 commented on js/home.js
> +                    return qq = '<span>' + qq + '</span>'
`qq` again

2021-12-01 17:11 UTC, sara219 commented on js/home.js
> +            suggBox.innerHTML = listData
`innerHTML` again

innerHTML creates a potential security risk for your website

2021-12-02 10:17 UTC, AseelL approved these changes
good job husam

2021-12-02 10:22 UTC, husamkamal commented
> good job husam

#

2021-12-02 10:58 UTC, sara219 approved these changes

2021-12-02 11:00 UTC, merged