clear input when select || click out input
GSG-CF04/FlowX pull request #39
Opened 2021-12-06 12:58 UTC by husamkamal

Relates #38

2021-12-06 15:09 UTC, sara219 approved these changes, later dismissed

2021-12-06 15:17 UTC, zaher-aa requested changes

2021-12-06 15:17 UTC, zaher-aa commented on js/home.js
> +    suggBox.textContent=""
Add spaces between the assign symbol and other stuff 😅
`inputField.value = ""`
`suggBox.textContent = ""`

2021-12-06 15:17 UTC, zaher-aa commented on js/home.js
> +      inputBox.value=""
here too

2021-12-06 15:17 UTC, zaher-aa commented on js/home.js
> +        inputBox.value=""
and here

2021-12-06 15:31 UTC, zaher-aa requested changes

2021-12-06 15:31 UTC, zaher-aa commented on js/home.js
> +        inputBox.value=""
Why remove the input value when clicking outside the input field

2021-12-06 15:31 UTC, zaher-aa commented on js/home.js
> +      inputBox.value=""
Why remove the input value when selecting a place

2021-12-06 15:31 UTC, zaher-aa commented on js/home.js
> +    suggBox.textContent=""
Why remove the input value when searching for a place

2021-12-06 18:12 UTC, zaher-aa approved these changes

2021-12-06 19:06 UTC, zaher-aa approved these changes

2021-12-06 21:51 UTC, AseelL approved these changes

2021-12-07 05:51 UTC, sara219 approved these changes

2021-12-07 07:29 UTC, merged